import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import Main from "@/components/main/Main";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="font-proximaNova">
        <div className="font-proximaNova">
          <div className="w-full bg-blue-strong">
            <Header />
          </div>
          <Main />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
