import React from "react";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { HeaderProvider } from "@/context";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="bg-background-default font-Arial">
        <AuthProvider>
          <HeaderProvider>
            <Header />
            {children}
            <Footer />
          </HeaderProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
